### PR TITLE
Reorganize npm dependencies

### PR DESCRIPTION
**Pull request by tysongach**
Reorganize npm dependencies, as Neat doesn’t actually _depend_ on Gulp, these are only for development to run the contributing site.
- Break out development dependencies
- Update packages
- Swap `node-bourbon` for `bourbon`

Am I correctly including `node-sass` here? Neat does require Sass to run, so I think we should’ve been including a Sass compiler as a dependency?

### CODE REVIEW

**Comment by tysongach** [comment]
@BlakeWilliams Building on your https://github.com/thoughtbot/neat/pull/397, since Neat needs Sass to actually compile—and similar to how we [declare Sass as a dependency](https://github.com/thoughtbot/neat/blob/master/neat.gemspec#L26) on the Ruby side—am I correct in that we should be declaring `node-sass` as a dependency?

**Comment by BlakeWilliams** [comment]
Yeah, I think it should be declared as a dependency as well.

**Comment by wardpenney** [comment]
Looks good :shipit:

**Comment by whmii** [comment]
yarp

**Pull request merged**
