### PR TITLE
Add eyeglass support for neat.

### PR DESCRIPTION
**Pull request by chriseppstein**
following on to my patch for bourbon: https://github.com/thoughtbot/bourbon/pull/775

### CODE REVIEW

**Comment by wardpenney** [comment]
Thanks @chriseppstein. @tysongach can you take a look too plz?

**Comment by chriseppstein** [comment]
@tysongach need anything else on this on now that the bourbon PR has landed?

**Comment by jonstuebe** [comment]
is there a reason this hasn't been added yet?

**Comment by tysongach** [comment]
Merged as https://github.com/thoughtbot/neat/commit/2089166472aae63fe7d3bfe3357bafccb3c97bc4. Thanks, @chriseppstein!

**Pull request closed without merging**
