### PR TITLE
Update node-sass version to 4.1.1 in order to support binaries for Alpine Linux

### PR DESCRIPTION
**Pull request by kazazor**
This solves https://github.com/thoughtbot/neat/issues/519.

We currently use version ^3.4 which is actually version 3.13.1 and according to the release notes of node-sass there are no breaking changes what so ever: https://github.com/sass/node-sass/releases/tag/v4.0.0

### CODE REVIEW

**Comment by kazazor** [comment]
Once this PR will be merged, if approved, it should be as part of a patch version `1.8.1`.

**Comment by kazazor** [comment]
This is really small commit, can someone please take a look at it so we could resolve the Alpine issue?

**Comment by whmii** [comment]
@kazazor this Pr is currently set to master. I just wanted to make sure your intent was to merge it it to 1.8

**Comment by whmii** [comment]
We have switched 2.0 to master so I am going to update this pr to point at https://github.com/thoughtbot/neat/tree/v1-stable

**Comment by whmii** [comment]
@kazazor LGTM, I'll merge this in tomorrow 👍

**Comment by r33beers** [comment]
Just checking in on this, since it hasn't been merged yet. Also, is this a decision not to address #516?

**Comment by tysongach** [comment]
Merged as https://github.com/thoughtbot/neat/commit/439db5d4793df66398df40f78aba8039b4c4d945.

**Comment by tysongach** [comment]
I just cut v1.9 which includes this change.

**Pull request closed without merging**
