### PR TITLE
Remove deprecation warning from `reset-display`

### PR DESCRIPTION
**Pull request by whmii**
- https://github.com/thoughtbot/neat/issues/338

### CODE REVIEW

**Comment by tysongach** [comment]
Shouldn’t we just be able to remove lines `38`–`40` in `_row.scss`?

I’m a bit confused, but I don’t think that `reset-display` is attributed to the issue.

**Comment by tysongach** [comment]
The `reset-display` mixin is not used in any other mixin in Neat except for `reset-all`. So I don’t think it has no affect on the `row` mixin or its deprecated arguments.

**Comment by tysongach** [comment]
@whmii Any word on my comments above? Am I mistaken on how that works?

**Comment by Sxderp** [comment]
@tysongach The problem is the global variable $container-is-display-table.

The row() mixin changes this variable ([line 39](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_row.scss#L39)). The reset-display() also changes this variable ([line 13](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_reset-display.scss)).

When using row, you have to manually call reset-display() in order to reset the global variable. Before the most recent commits, they were trying to push the display-context() mixin which would have done this for you. The problem they had was trying to support the 'deprecated' method as well (keeping the globals in row and not using is-display-table()).

**Comment by dcalhoun** [comment]
@whmii I am a little confused about what is the correct usage of `display`.

### Example 1
```scss
@include row(table)
```

### Example 2
```scss
@include display-context(table) {
  @include row();
}
```

Example 1 throws a deprecation warning. Example 2 appears to have no impact on the display for the row. What is the correct usage of `display` in `v1.8.0`?

**Comment by kgcreative** [comment]
Deprecation warnings don't affect 1.x - they are there to let you know which features will not be present in the next major release

**Comment by dcalhoun** [comment]
@kgcreative Understood. From my experience, library deprecations warnings can be resolved prior to upgrading. The idea being that if you "take care of" all the warnings, upgrading to the major release is a straight-forward process. The deprecation warnings are a "checklist" to get ready for the upgrade.

It would appear that it is impossible to resolve Neat's "deprecation warnings" without upgrading to "the next major release", which sort of defeats the purpose of including them in my compilation logs for `1.x.x` IMO.

**Pull request merged**
