### PR TITLE
Added a small mixin to quickly make elements span n wide.

### PR DESCRIPTION
**Pull request by iamkirkbater**

### CODE REVIEW

**Comment by tysongach** [comment]
@iamkirkbater Can you provide an example use-case, or scenario in which this would be useful and solve a problem?

**Comment by iamkirkbater** [comment]
So I'm currently building a site where we have a staff page. Each staff member has a photo, name, a title, and a button to view a bio.

When the browser is greater than 900px wide, we want to display 4 people wide.  When the browser is between 601 and 899px wide, we display 3 wide.  When it's between 455 and 600px wide, we display 2 wide.

Here's the code that I just finished for this:

```scss
// my own custom _mixins.scss
@mixin between($min, $max) {
  @media (min-width: #{$min}) and (max-width: #{$max}) { @content }
}

@mixin min($size) {
  @media (min-width: #{$size}) { @content }
}

@mixin n-wide($n) {
  @include span-columns(12 / $n);
  @include omega(#{$n}n);
}
```

```scss
// _person.scss
.person {

  @include between(455px, 600px) {
    @include n-wide(2);
  }

  @include between(601px, 899px) {
    @include n-wide(3)
  }

  @include min(900px) {
    @include n-wide(4);
  }
}
```

Basically, the idea is to save having to write the following for every breakpoint:

```scss
@include min(900px) {
  @include span-columns(3);
  @include omega(4n);
}
```

It's already in my `_mixins.scss` which I include in every project, but I figured that other people may find this useful.  

Here's the site I'm currently working on (work in progress) where I use this: https://www-staging.rit.edu/affiliate/nysp2i/about/advisory-board.

**Comment by tysongach** [comment]
Thanks for the explanation.

What happens, though, if someone isn’t using 12 columns, and maybe even a different quantity of columns at each breakpoint?

**Comment by iamkirkbater** [comment]
Hmm, great point.  I sometimes forget that not everyone uses the same workflow.

I could always make `n-wide` take a second, optional argument for column count?  I think I saw somewhere else that there was a contextual variable for finding the amount of columns in a given breakpoint?  I'll try to see if I can find what I was looking at.

The last thing I want to do is have to make developers re-declare the same things over and over again because the amount of columns they have changes, as that's exactly what this is trying to prevent :)

**Comment by tysongach** [comment]
Definitely.

A primary goal for 2.0 is to eliminate `omega` all-together, which would also deem this mixin/approach unnecessary.

**Comment by whmii** [comment]
@iamkirkbater yep, as @tysongach the only branch that will be introducing new features is `2.0` which does not use `omega`. sorry.

**Comment by iamkirkbater** [comment]
It's all good.  If I would have known that I probably wouldn't have threw it out there.  Keep up the great work!

**Pull request closed without merging**
