### PR TITLE
Specify where to set `$visual-grid` to true

### PR DESCRIPTION
**Pull request by jessieay**
* Had to watch a YouTube video of Kyle using it to figure out why
  setting it to true in a random `scss` file wasn't working

Shout out to @maya for pointing out that this is even a thing!

### CODE REVIEW

**Comment by maya** [comment]
Said video: https://youtu.be/8ItNE_DX6Cc?t=32m18s

**Comment by jessieay** [comment]
ps - 42.5k views on that vid!? @kylefiedler is srsly famous :sunglasses:

**Comment by tysongach** [comment]
JESSIE! :wave: 

So to clarify, the grid wasn’t showing for you and the change here is to indicate that you must edit the variable directly in `_visual-grid.scss`?

**Comment by jessieay** [comment]
@tysongach 

1. :wave:  

2. You got it! This was in a Jekyll project, not Rails, so it could be an issue specific to that framework, but we were setting it to `true` in a scss file and were not seeing the grid. When we found the `settings` file and changed it there, it WORKED :rainbow: :rainbow:

**Comment by wardpenney** [comment]
Haha @jessieay! I think the issue here is that Neat asks developers to `@import` `neat-helpers` before importing Neat itself. And that variable is accessed within `neat-helpers`

**Comment by wardpenney** [comment]
I really want to deprecate the need to import `neat-helpers` before importing `neat`. It is only dependent on the `neat-breakpoint` usage, and I don't really think this framework needs to *instantiate* breakpoints. There is marginal gain to the developer here.

**Comment by wardpenney** [comment]
@jessieay does it work if you set it to true before importing the `neat-helpers`?

**Comment by jessieay** [comment]
@wardpenney are you laughing at me :question: ...bc it appears that you are the one wearing a horse mask in this convo :horse: 

I am not sure I understand your explanation. This is not a Rails project so I don't know if it would be the same issue. Maya just set it to `true` in one of this file and it didn't work: https://github.com/18F/web-design-standards/blob/18f-pages-staging/assets/_scss/core/_grid-settings.scss

**Comment by wardpenney** [comment]
I don't know why I used "haha" it should have been "hey hey!" 

I notice you have in the [sass pathway](https://github.com/18F/web-design-standards/blob/18f-pages-staging/assets/_scss/all.scss) `@import 'core/grid-settings';` is called after `@import 'lib/neat/neat';` 

In this case, your `gird_settings` will have already been set by neat defaults, and be disregarded. So you need that to come before the neat import. And to turn on the grid, you would have to:

1. Turn on the variable
* Then import `neat_helpers`
* Then import your `grid_settings`
* Then import neat itself

You probably haven't noticed the bug if you haven't tried to change the default breakpoints :hankey:

**Comment by jessieay** [comment]
@wardpenney :fries: 

Thank you for the detailed explanation. Does this mean it is project-specific that the visual grid worked by updating the value of `visual-grid` in https://github.com/18F/web-design-standards/blob/18f-pages-staging/assets/_scss/lib/neat/settings/_visual-grid.scss ? I think that having people update within there makes total sense as long as it is documented.

If it only worked for us because of some project-specific settings, I can update the PR to include the the steps you included in the comment above.

**Comment by jessieay** [comment]
(also, I am still totally not a designer, just happened to be sitting by Maya when she made this change, so there is a high probability I am completely misunderstanding what you are saying)

**Comment by wardpenney** [comment]
@jessieay oh yeah I hear that, and it does work. But, I am not in favor of advising to change the core of the framework to get the effect. It is not the best setup, but for someone using a gem or node package, they don't have that kind of access.

Maybe something like:

```
By setting `$visual-grid` to `true` prior to importing`neat-helpers` (or prior to importing `neat` itself if you are using the default breakpoints), you can display the base grid in the background (default) or as an overlay. You can even change the color and opacity of the grid-lines by overriding the default settings as detailed in the section below.
```

**Comment by wardpenney** [comment]
I know that sounds legalistic, so maybe something super basic:

```
By setting `$visual-grid` to `true` at the top of your root Sass file...
```

**Comment by jessieay** [comment]
@wardpenney as a non-SCSS superstar, the second comment isn't clear to me. Will go for the first long one!

**Comment by wardpenney** [comment]
Ahh yeah I'm using terminology I invented... How about:

By setting `$visual-grid` to `true` before you `@import` Neat...

**Comment by wardpenney** [comment]
I just don't wanna confuse everyone more :dizzy_face:

**Comment by jessieay** [comment]
@wardpenney my question about that text is: do you set this in the file with `@import` (manifest, I believe it is called) or in a file that is imported before?

**Comment by wardpenney** [comment]
@jessieay you would assign it prior to the `@import` of anything to do with neat. And for all users, that would be in the file you control (the one that does the importing). My wording sucks, is there a way to say that better?

**Comment by wardpenney** [comment]
Assuming a lot of developer end-users can not edit the content of Neat itself.

**Comment by jessieay** [comment]
So set `$visual-grid: true;` directly in this file, in our case? https://github.com/18F/web-design-standards/blob/317abf5c9f629c7c68bfff920c4de4f0d869ad17/assets/_scss/all.scss#L4

**Comment by wardpenney** [comment]
@jessieay I think so, but @tysongach and I are looking at it now. There's something going on we haven't nailed down yet. What I was saying might be a red herring. Will get back to u

**Comment by jessieay** [comment]
kk :heart: to u guyz for looking into this -- I owe you a Philz!!!

**Comment by tysongach** [comment]
@jessieay @maya Ho-hum, this visual grid stuff always gets me :confused: But @wardpenney and I had a quick pow-wow and hopefully our findings help you out!

1. From a high-level, both Bourbon and Neat are _libraries_. So best practice (for future upgrading!) is that we shouldn’t be editing the source directly, which includes not editing variables like this within Neat’s `_visual-grid.scss` partial. Typically when we use them as gems in a Rails environment, directly editing the source is an obviously impossible task. But since this is not a Rails app, just want to clarify.
2. The key—and what we have failed to make clear—is that these `$visual-grid-*` variables _must_ be defined _before_ importing Neat.

There’s many ways to accomplish this, but here’s probably how I would go about it with your set up:

Create a `_neat-settings.scss` partial inside `assets/_scss/lib` and park your customized visual grid variables in there:

```scss
$visual-grid: true;
$visual-grid-color: blue;
$visual-grid-opacity: 0.2;
```

Then import that partial inside your main Sass manifest (`assets/_scss/all.scss`) right before Neat:

```scss
@import 'lib/bourbon/bourbon';
@import 'lib/neat-settings';
@import 'lib/neat/neat';
@import 'lib/normalize';
```

This allows you to cleanly and easily update Neat at any time since we haven’t edited anything directly in there. One slight downfall is that your `lib` directory is not _exclusively_ libraries: it now has your own tweaks within it and that could cause a smidgen of confusion for people trying to find this stuff.

Sorry for our documentation not being clear on this one! We’ll have to update that! We also realize this could be much simpler and we have better methods these days, so we hope to alleviate this whole conundrum in the future.

**Comment by jessieay** [comment]
@tysongach Thank you for the explanation - I think I am finally understanding what's going on here. 

I just updated the proposed README changes in this PR in a way that will help others but is not specific to how our particular project is set up. 

What do you think?

:ice_cream:

**Comment by tysongach** [comment]
Merged as https://github.com/thoughtbot/neat/commit/824e86bb8fd799c026cfd5bd53f49d70b8a21116. Thank you, @jessieay!

**Pull request closed without merging**
