### PR TITLE
Remove node-sass dependency

### PR DESCRIPTION
**Pull request by Subash**
It is not really required to use neat.

### CODE REVIEW

**Comment by tysongach** [comment]
The build is breaking from this:

```
Gem::InstallError: scss_lint requires Ruby version >= 2.
Using neat 1.8.0 from source at .
Installing cucumber 2.4.0
Installing rspec 3.5.0
Installing ffi 1.9.14
Installing json 1.8.3
An error occurred while installing scss_lint (0.50.3), and Bundler cannot
continue.
Make sure that `gem install scss_lint -v '0.50.3'` succeeds before bundling.
```

Are we setting a specific Ruby version somewhere? If not, it might resolve this?

**Comment by tysongach** [comment]
I put up a PR to resolve the build failure: https://github.com/thoughtbot/neat/pull/508.

**Comment by tysongach** [comment]
@whmii With https://github.com/thoughtbot/neat/commit/bef91b781ad5a13ebde9324bba18d8685768a3f5, can this PR be closed?

**Comment by whmii** [comment]
Lets merge [https://github.com/thoughtbot/neat/pull/508]

However merging this in would imply that it will/may end up in a future `v1.X.X` which is not the case. This issue has been addressed in [https://github.com/thoughtbot/neat/issues/505] so more details on the overall issue there. Because the use of `node-sass` has been an isue for some users, we have created a branch at [https://github.com/thoughtbot/neat/tree/neat-1.8.0-node-sass] which contains this change.

**Pull request closed without merging**
