### PR TITLE
Add core grid functionality ported from whmii/cask

### PR DESCRIPTION
**Pull request by whmii**
Pulled in files from whmii/cask as of 3f9b71439c6c96123ee177b1f1d00295968e1eeb

For a complete history see https://github.com/whmii/cask

### CODE REVIEW

**Comment by tysongach** [comment]
:-1: I’d rather pull in smaller chunks so we can add tests along the way, as well as documentation. Otherwise we have to backfill all of that and it’s highly likely we’ll introduce either bugs, or leave something out.

**Comment by wardpenney** [comment]
Yeah, agree with :-1:, too much too fast. IMO, this introduces too many configuration points and access of global variables. If we handle the features one by one, we should be able to process easier:

* Simple grid
* Pushing / Pulling / Shifting (are these different?)
* Handle zero errors (if needed?)

I love the calc grid, though.

Also, I would like it if we made the example usage in contrib as well, so we can tell how the end user would consume it.

**Comment by whmii** [comment]
agree, this pr is was meant as a talking point for this very discussion 😘

**Comment by wardpenney** [comment]
Makes sense!

**Comment by tysongach** [comment]
:100:

**Pull request closed without merging**
