### PR TITLE
Decouple Neat from Bourbon

### PR DESCRIPTION
**Pull request by wardpenney**
I think decoupling Neat from Bourbon will have a few big positives:

* Expand Neat's potential user base
* Simplified install of Neat
* Clearer docs (no more `bourbon` before `grid_settings` before `neat` confusion)

### CODE REVIEW

**Comment by joshuaogle** [comment]
I really thought there would be more to this. :+1:

I assume you're still alright with it being part of the "Bourbon Suite", just not dependent?

**Comment by wardpenney** [comment]
Yeah pretty much. I like how it's all informed together as a great total solution.

**Comment by kaishin** [comment]
I think this is the right direction to go. However I think this should be done in 2.0 with better name-spacing  and updated tests.

**Comment by tysongach** [comment]
:+1:

**Comment by wardpenney** [comment]
Yes good point, this is better for 2.0. I'll make the PR to hit 2.0 branch.

**Pull request closed without merging**
