### PR TITLE
Remove float from grid-collapse

### PR DESCRIPTION
**Pull request by kgcreative**
per https://github.com/thoughtbot/neat/issues/528#issuecomment-278168504

### CODE REVIEW

**Comment by whmii** [comment]
screen shot 2017-02-08 at 9 41 45 pm

I have tested out this feature out in [contrib](https://github.com/thoughtbot/neat/blob/master/CONTRIBUTING.md) and it results in practical changes real changes.

For those using collapse on the grid container it is important to remember that this will cause the container to overflow the view resulting in a x-scroll. To resolve this you will need to add `overflow-x: hidden` to the collapsed object's parent. This, however is a secondary use-case as the primary function of `grid-collapse()` is to allow for easily nested grids.

I have created a short gif of what this `overflow-x` issue looks like. It feels like the sort of thing that could act differently from browser to browser so use with discretion.

grid-collapse with overflow-x hidden

Overall, this change looks good to me and barring objection will get merged tomorrow AM

**Comment by whmii** [comment]
@kgcreative your changes did not update the test suite. I have pushed up a fixup commit to address this. Can you fixup these changes in to you commit. https://github.com/thoughtbot/neat/commit/c9524404465ab4726f9334c6dc9d18709a64995d

**Comment by whmii** [comment]
```
git fetch && git cherry-pick c9524404465ab4726f9334c6dc9d18709a64995d
```

**Comment by whmii** [comment]
```
git rebase origin/master -i
```

**Comment by kgcreative** [comment]
@whmii - yep! I'll do this shortly

**Comment by whmii** [comment]
screen shot 2017-02-10 at 2 35 13 pm

Merged. I had to rebase it again so this PR wont autoclose

**Pull request closed without merging**
